apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: kubeaudit-cloudwatch
  name: kubeaudit-cloudwatch
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: kubeaudit-cloudwatch
  template:
    metadata:
      labels:
        app: kubeaudit-cloudwatch
    spec:
      serviceAccountName: kubeaudit-cloudwatch
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: kubeaudit-cloudwatch
        ports:
        - containerPort: 4516
        volumeMounts:
        - mountPath: {{ .Values.k8s.audit_log_path }}
          name: var-log-kubernetes
        env:
        - name: AWS_REGION
          value: {{ .Values.AWS.AWS_REGION }}
        - name: AWS_ACCESS_KEY_ID
          valueFrom: 
            secretKeyRef: 
              name: kubeaudit-cloudwatch 
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom: 
            secretKeyRef: 
              name: kubeaudit-cloudwatch 
              key: AWS_SECRET_ACCESS_KEY
        - name: CLOUDWATCH_LOGGROUP
          value: {{ .Values.cloudwatch.loggroup }}
        - name: K8S_NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumes:
        - hostPath: 
            path: {{ .Values.k8s.audit_log_path }}
            type: DirectoryOrCreate
          name: var-log-kubernetes