apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubeaudit-cloudwatch
  name: kubeaudit-cloudwatch
  namespace: lacework
spec:
  ports:
  - name: 4516-4516
    port: 4516
    protocol: TCP
    targetPort: 4516
  selector:
    app: kubeaudit-cloudwatch
  type: ClusterIP
